---
platform: linux

image_resource:
  type: registry-image
  source:
    aws_access_key_id: ((aws-key))
    aws_secret_access_key: ((aws-secret))
    repository: ((image))
    aws_region: us-gov-west-1
    semver_constraint: ">= 1.0.0"

inputs:
- name: cf-manifests
outputs:
- name: integration-config

run:
  path: cf-manifests/ci/acceptance-tests-config.sh
